cat("start of series in yyyy-mm-dd format")
data = as.Date(scan(what = " ", nmax = 1))
cat("what series size do you want to get?")
size = scan(nmax=1)
cat("minimum value")
minimum = scan(nmax=1)
cat("minimum value")
maximum  = scan(nmax=1)
x = seq(1,size)
values = runif(size, min=minimum, max=maximum)
date = data + x
table <- data.frame(date = date, target = values)
write.csv(table, "random_series.csv", row.names = FALSE) 
